### ISSUE TITLE
Remove pandas and plotly from dependency

### ISSUE THREAD

**Issue by mzy2240** [ramedina86/streamsync#4]
Congratulations on the release! 

Is it possible to remove pandas and plotly from dependency?

**Comment by ramedina86** [comment]
Thank you! I gave this some thought and I'll move forward with it.

My only concern was that it makes promoting the project slightly harder, as

```
pip install streamsync[ds]
streamsync hello
```

is less straightforward than

```
pip install streamsync
streamsync hello
```

But that convenience is penalising those that don't need those massive packages installed.

I'll also add a warning message during `streamsync hello` to tell people to install `streamsync[ds]` if the packages aren't found, which should minimise the negative impact.
